language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
    - composer test
